exports.WEEKDAY_OFFSET = {
    'domingo': 0,
    'dom': 0,
    'segunda': 1,
    'seg': 1,
    'terça': 2,
    'terca': 2,
    'quarta': 3,
    'qua': 3,
    'quinta': 4,
    'qui': 4,
    'sexta': 5,
    'sex': 5,
    'sábado': 6,
    'sabado': 6,
    'sáb': 6,
    'sab': 6,}

exports.WEEKDAY_OFFSET_PATTERN = '(?:' + Object.keys(exports.WEEKDAY_OFFSET).join('|') +')';


exports.MONTH_OFFSET = {
    'janeiro': 1,
    'jan': 1,
    'jan\\.': 1,
    'fevereiro': 2,
    'fev': 2,
    'fev\\.': 2,
    'março': 3,
    'marco': 3,
    'mar': 3,
    'mar\\.': 3,
    'abril': 4,
    'abr': 4,
    'abr\\.': 4,
    'maio': 5,
    'mai': 5,
    'mai\\.': 5,
    'junho': 6,
    'jun': 6,
    'jun\\.': 6,
    'julho': 7,
    'jul': 7,
    'jul\\.': 7,
    'agosto': 8,
    'ago': 8,
    'ago\\.': 8,
    'setembro': 9,
    'set': 9,
    'set\\.': 9,
    'outubro': 10,
    'out': 10,
    'out\\.': 10,
    'novembro': 11,
    'nov': 11,
    'nov\\.': 11,
    'dezembro': 12,
    'dez': 12,
    'dez\\.': 12,
}
exports.MONTH_OFFSET_PATTERN = '(?:' + Object.keys(exports.MONTH_OFFSET).join('|') +')';

exports.INTEGER_WORDS = {
    'zero' : 0,
    'um' : 1,
    'uma' : 1,
    'dois' : 2,
    'duas' : 2,
    'três' : 3,
    'tres' : 3,
    'quatro' : 4,
    'cinco' : 5,
    'seis' : 6,
    'sete' : 7,
    'oito' : 8,
    'nove' : 9,
    'dez' : 10,
    'onze' : 11,
    'doze' : 12,
    'treze' : 13,
    'catorze' : 14,
    'quatorze' : 14,
    'quinze' : 15,
    'dezesseis' : 16,
    'dezesete' : 17,
    'dezoito' : 18,
    'dezenove' : 19,
    'vinte' : 20,
};
exports.INTEGER_WORDS_PATTERN = '(?:' + Object.keys(exports.INTEGER_WORDS).join('|') +')';
